/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UEContextManagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetSmsf3gppAccess - retrieve the SMSF registration for 3GPP access information
func GetSmsf3gppAccess(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
