/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/nrf/internal/sbi/management"
)

func (s *Server) getNfManagementRoute() []Route {
	return []Route{
		{
			"Index",
			http.MethodGet,
			"/",
			func(c *gin.Context) {
				c.JSON(http.StatusOK, "free5gc")
			},
		},
		{
			"DeregisterNFInstance",
			http.MethodDelete,
			"/nf-instances/:nfInstanceID",
			management.HTTPDeregisterNFInstance,
		},
		{
			"GetNFInstance",
			http.MethodGet,
			"/nf-instances/:nfInstanceID",
			management.HTTPGetNFInstance,
		},
		{
			"RegisterNFInstance",
			http.MethodPut,
			"/nf-instances/:nfInstanceID",
			management.HTTPRegisterNFInstance,
		},
		{
			"UpdateNFInstance",
			http.MethodPatch,
			"/nf-instances/:nfInstanceID",
			management.HTTPUpdateNFInstance,
		},
		{
			"GetNFInstances",
			http.MethodGet,
			"/nf-instances",
			management.HTTPGetNFInstances,
		},
		{
			"RemoveSubscription",
			http.MethodDelete,
			"/subscriptions/:subscriptionID",
			management.HTTPRemoveSubscription,
		},
		{
			"UpdateSubscription",
			http.MethodPatch,
			"/subscriptions/:subscriptionID",
			management.HTTPUpdateSubscription,
		},
		{
			"CreateSubscription",
			http.MethodPost,
			"/subscriptions",
			management.HTTPCreateSubscription,
		},
	}
}
