/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package DataRepository_test

import (
	"context"
	"go.mongodb.org/mongo-driver/bson"
	"free5gc/src/udr/logger"
	"net/http"
	"testing"

	"free5gc/lib/Nudr_DataRepository"
	"free5gc/lib/openapi/models"

	"github.com/google/go-cmp/cmp"
)

// ModifyPpData - modify the provisioned parameter data
func TestModifyPpData(t *testing.T) {
	runTestServer(t)

	connectMongoDB(t)

	// Drop old data
	collection := Client.Database("free5gc").Collection("subscriptionData.ppData")
	collection.DeleteOne(context.TODO(), bson.M{"ueId": "imsi-0123456789"})

	// Set client and set url
	client := setTestClient(t)

	// Set test data
	ueId := "imsi-0123456789"
	testData := models.PpData{
		CommunicationCharacteristics: &models.CommunicationCharacteristics{
			PpSubsRegTimer: &models.PpSubsRegTimer{
				SubsRegTimer: 1,
				AfInstanceId: "1",
				ReferenceId:  1,
			},
			PpActiveTime: &models.PpActiveTime{
				ActiveTime:   1,
				AfInstanceId: "1",
				ReferenceId:  1,
			},
			PpDlPacketCount: 1,
		},
	}
	insertTestData := toBsonM(testData)
	insertTestData["ueId"] = ueId
	collection.InsertOne(context.TODO(), insertTestData)

	{
		// Check patch data (Use RESTful GET)
		var getppDataParamOpts Nudr_DataRepository.GetppDataParamOpts
		ppData, res, err := client.ParameterProvisionDocumentApi.GetppData(context.TODO(), ueId, &getppDataParamOpts)
		if err != nil {
			logger.AppLog.Panic(err)
		}

		if status := res.StatusCode; status != http.StatusOK {
			t.Errorf("handler returned wrong status code: got %v want %v",
				status, http.StatusOK)
		}
		if cmp.Equal(testData, ppData, Opt) != true {
			t.Errorf("handler returned unexpected body: got %v want %v",
				ppData, testData)
		}
	}

	patchItemArray := []models.PatchItem{
		{
			Op:    models.PatchOperation_REPLACE,
			Path:  "/communicationCharacteristics/ppDlPacketCount",
			Value: 2,
		},
	}
	patchData := models.PpData{
		CommunicationCharacteristics: &models.CommunicationCharacteristics{
			PpSubsRegTimer: &models.PpSubsRegTimer{
				SubsRegTimer: 1,
				AfInstanceId: "1",
				ReferenceId:  1,
			},
			PpActiveTime: &models.PpActiveTime{
				ActiveTime:   1,
				AfInstanceId: "1",
				ReferenceId:  1,
			},
			PpDlPacketCount: 2,
		},
	}

	{
		// Patch data (Use RESTful PATCH)
		res, err := client.ProvisionedParameterDataDocumentApi.ModifyPpData(context.TODO(), ueId, patchItemArray)
		if err != nil {
			logger.AppLog.Panic(err)
		}

		if status := res.StatusCode; status != http.StatusNoContent {
			t.Errorf("handler returned wrong status code: got %v want %v",
				status, http.StatusNoContent)
		}
	}

	{
		// Check patch data (Use RESTful GET)
		var getppDataParamOpts Nudr_DataRepository.GetppDataParamOpts
		ppData, res, err := client.ParameterProvisionDocumentApi.GetppData(context.TODO(), ueId, &getppDataParamOpts)
		if err != nil {
			logger.AppLog.Panic(err)
		}

		if status := res.StatusCode; status != http.StatusOK {
			t.Errorf("handler returned wrong status code: got %v want %v",
				status, http.StatusOK)
		}

		if cmp.Equal(patchData, ppData, Opt) != true {
			t.Errorf("handler returned unexpected body: got %v want %v",
				ppData, patchData)
		}
	}

	// Clean test data
	collection.DeleteOne(context.TODO(), bson.M{"ueId": "imsi-0123456789"})
}
