/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Communication

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

// NonUeN2MessageTransfer - Namf_Communication Non UE N2 Message Transfer service Operation
func NonUeN2MessageTransfer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
