/*
 * Nausf_SoRProtection Service
 *
 * AUSF SoR Protection Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SoRProtection

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// SupiUeSorPost -
func SupiUeSorPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
