/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SubscriberDataManagement

import (
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	AddService(router)
	return router
}

func oneLayerPathHandlerFunc(c *gin.Context) {
	var supi = c.Param("supi")
	for _, route := range oneLayerPathRouter {
		if strings.Contains(route.Pattern, supi) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}

	// special case for :supi
	if c.Request.Method == strings.ToUpper("Get") {
		GetSupi(c)
		return
	}

	c.String(http.StatusNotFound, "404 page not found")
}

func twoLayerPathHandlerFunc(c *gin.Context) {
	var supi = c.Param("supi")
	var op = c.Param("subscriptionId")

	// for "/shared-data-subscriptions/:subscriptionId"
	if supi == "shared-data-subscriptions" && strings.ToUpper("Delete") == c.Request.Method {
		UnsubscribeForSharedData(c)
		return
	}

	// for "/:gpsi/id-translation-result"
	if op == "id-translation-result" && strings.ToUpper("Get") == c.Request.Method {
		c.Params = append(c.Params, gin.Param{"gpsi", c.Param("supi")})
		GetIdTranslationResult(c)
		return
	}

	for _, route := range twoLayerPathRouter {
		if strings.Contains(route.Pattern, op) && route.Method == c.Request.Method {
			route.HandlerFunc(c)
			return
		}
	}

	c.String(http.StatusNotFound, "404 page not found")
}

func threeLayerPathHandlerFunc(c *gin.Context) {
	var op = c.Param("subscriptionId")

	// for "/:supi/sdm-subscriptions/:subscriptionId"
	if op == "sdm-subscriptions" && strings.ToUpper("Delete") == c.Request.Method {
		var tmpParams gin.Params
		tmpParams = append(tmpParams, gin.Param{"supi", c.Param("supi")})
		tmpParams = append(tmpParams, gin.Param{"subscriptionId", c.Param("thirdLayer")})
		c.Params = tmpParams
		Unsubscribe(c)
		return
	}

	// for "/:supi/am-data/sor-ack"
	if op == "am-data" && strings.ToUpper("Put") == c.Request.Method {
		Info(c)
		return
	}

	c.String(http.StatusNotFound, "404 page not found")
}

func AddService(engine *gin.Engine) *gin.RouterGroup {
	group := engine.Group("/nudm-sdm/v1")

	for _, route := range routes {
		switch route.Method {
		case "GET":
			group.GET(route.Pattern, route.HandlerFunc)
		case "POST":
			group.POST(route.Pattern, route.HandlerFunc)
		case "PUT":
			group.PUT(route.Pattern, route.HandlerFunc)
		case "DELETE":
			group.DELETE(route.Pattern, route.HandlerFunc)
		case "PATCH":
			group.PATCH(route.Pattern, route.HandlerFunc)
		}
	}

	var oneLayerPath = "/:supi"
	group.Any(oneLayerPath, oneLayerPathHandlerFunc)

	var twoLayerPath = "/:supi/:subscriptionId"
	group.Any(twoLayerPath, twoLayerPathHandlerFunc)

	var threeLayerPath = "/:supi/:subscriptionId/:thirdLayer"
	group.Any(threeLayerPath, threeLayerPathHandlerFunc)

	return group
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},
}

var specialRouter = Routes{
	{
		"GetIdTranslationResult",
		strings.ToUpper("Get"),
		"/:gpsi/id-translation-result",
		GetIdTranslationResult,
	},

	{
		"UnsubscribeForSharedData",
		strings.ToUpper("Delete"),
		"/shared-data-subscriptions/:subscriptionId",
		UnsubscribeForSharedData,
	},

	{
		"ModifyForSharedData",
		strings.ToUpper("Patch"),
		"/shared-data-subscriptions/:subscriptionId",
		ModifyForSharedData,
	},
}

var oneLayerPathRouter = Routes{
	{
		"GetSupi",
		strings.ToUpper("Get"),
		"/:supi",
		GetSupi,
	},

	{
		"GetSharedData",
		strings.ToUpper("Get"),
		"/shared-data",
		GetSharedData,
	},

	{
		"SubscribeToSharedData",
		strings.ToUpper("Post"),
		"/shared-data-subscriptions",
		SubscribeToSharedData,
	},
}

var twoLayerPathRouter = Routes{
	{
		"GetAmData",
		strings.ToUpper("Get"),
		"/:supi/am-data",
		GetAmData,
	},

	{
		"GetSmfSelectData",
		strings.ToUpper("Get"),
		"/:supi/smf-select-data",
		GetSmfSelectData,
	},

	{
		"GetSmsMngData",
		strings.ToUpper("Get"),
		"/:supi/sms-mng-data",
		GetSmsMngData,
	},

	{
		"GetSmsData",
		strings.ToUpper("Get"),
		"/:supi/sms-data",
		GetSmsData,
	},

	{
		"GetSmData",
		strings.ToUpper("Get"),
		"/:supi/sm-data",
		GetSmData,
	},

	{
		"GetNssai",
		strings.ToUpper("Get"),
		"/:supi/nssai",
		GetNssai,
	},

	{
		"Subscribe",
		strings.ToUpper("Post"),
		"/:supi/sdm-subscriptions",
		Subscribe,
	},

	{
		"GetTraceData",
		strings.ToUpper("Get"),
		"/:supi/trace-data",
		GetTraceData,
	},

	{
		"GetUeContextInSmfData",
		strings.ToUpper("Get"),
		"/:supi/ue-context-in-smf-data",
		GetUeContextInSmfData,
	},

	{
		"GetUeContextInSmsfData",
		strings.ToUpper("Get"),
		"/:supi/ue-context-in-smsf-data",
		GetUeContextInSmsfData,
	},
}

var threeLayerPathRouter = Routes{
	{
		"Unsubscribe",
		strings.ToUpper("Delete"),
		"/:supi/sdm-subscriptions/:subscriptionId",
		Unsubscribe,
	},

	{
		"Info",
		strings.ToUpper("Put"),
		"/:supi/am-data/sor-ack",
		Info,
	},

	{
		"PutUpuAck",
		strings.ToUpper("Put"),
		"/:supi/am-data/upu-ack",
		PutUpuAck,
	},

	{
		"Modify",
		strings.ToUpper("Patch"),
		"/:supi/sdm-subscriptions/:subscriptionId",
		Modify,
	},
}

var routesBackup = Routes{
	{
		"Index",
		"GET",
		"/",
		Index,
	},

	{
		"GetAmData",
		strings.ToUpper("Get"),
		"/:supi/am-data",
		GetAmData,
	},

	{
		"Info",
		strings.ToUpper("Put"),
		"/:supi/am-data/sor-ack",
		Info,
	},

	{
		"GetSupi",
		strings.ToUpper("Get"),
		"/:supi",
		GetSupi,
	},

	{
		"GetSharedData",
		strings.ToUpper("Get"),
		"/shared-data",
		GetSharedData,
	},

	{
		"GetSmfSelectData",
		strings.ToUpper("Get"),
		"/:supi/smf-select-data",
		GetSmfSelectData,
	},

	{
		"GetSmsMngData",
		strings.ToUpper("Get"),
		"/:supi/sms-mng-data",
		GetSmsMngData,
	},

	{
		"GetSmsData",
		strings.ToUpper("Get"),
		"/:supi/sms-data",
		GetSmsData,
	},

	{
		"GetSmData",
		strings.ToUpper("Get"),
		"/:supi/sm-data",
		GetSmData,
	},

	{
		"GetNssai",
		strings.ToUpper("Get"),
		"/:supi/nssai",
		GetNssai,
	},

	{
		"Subscribe",
		strings.ToUpper("Post"),
		"/:supi/sdm-subscriptions",
		Subscribe,
	},

	{
		"SubscribeToSharedData",
		strings.ToUpper("Post"),
		"/shared-data-subscriptions",
		SubscribeToSharedData,
	},

	{
		"Unsubscribe",
		strings.ToUpper("Delete"),
		"/:supi/sdm-subscriptions/:subscriptionId",
		Unsubscribe,
	},

	{
		"UnsubscribeForSharedData",
		strings.ToUpper("Delete"),
		"/shared-data-subscriptions/:subscriptionId",
		UnsubscribeForSharedData,
	},

	{
		"GetTraceData",
		strings.ToUpper("Get"),
		"/:supi/trace-data",
		GetTraceData,
	},

	{
		"GetUeContextInSmfData",
		strings.ToUpper("Get"),
		"/:supi/ue-context-in-smf-data",
		GetUeContextInSmfData,
	},

	{
		"GetUeContextInSmsfData",
		strings.ToUpper("Get"),
		"/:supi/ue-context-in-smsf-data",
		GetUeContextInSmsfData,
	},

	{
		"GetIdTranslationResult",
		strings.ToUpper("Get"),
		"/:gpsi/id-translation-result",
		GetIdTranslationResult,
	},
}
