// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/app/app.go
//
// Generated by this command:
//
//	mockgen -source=pkg/app/app.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	context "github.com/free5gc/nssf/internal/context"
	factory "github.com/free5gc/nssf/pkg/factory"
	gomock "go.uber.org/mock/gomock"
)

// MockNssfApp is a mock of NssfApp interface.
type MockNssfApp struct {
	ctrl     *gomock.Controller
	recorder *MockNssfAppMockRecorder
}

// MockNssfAppMockRecorder is the mock recorder for MockNssfApp.
type MockNssfAppMockRecorder struct {
	mock *MockNssfApp
}

// NewMockNssfApp creates a new mock instance.
func NewMockNssfApp(ctrl *gomock.Controller) *MockNssfApp {
	mock := &MockNssfApp{ctrl: ctrl}
	mock.recorder = &MockNssfAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNssfApp) EXPECT() *MockNssfAppMockRecorder {
	return m.recorder
}

// Config mocks base method.
func (m *MockNssfApp) Config() *factory.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config")
	ret0, _ := ret[0].(*factory.Config)
	return ret0
}

// Config indicates an expected call of Config.
func (mr *MockNssfAppMockRecorder) Config() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockNssfApp)(nil).Config))
}

// Context mocks base method.
func (m *MockNssfApp) Context() *context.NSSFContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(*context.NSSFContext)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockNssfAppMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockNssfApp)(nil).Context))
}

// SetLogEnable mocks base method.
func (m *MockNssfApp) SetLogEnable(enable bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogEnable", enable)
}

// SetLogEnable indicates an expected call of SetLogEnable.
func (mr *MockNssfAppMockRecorder) SetLogEnable(enable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogEnable", reflect.TypeOf((*MockNssfApp)(nil).SetLogEnable), enable)
}

// SetLogLevel mocks base method.
func (m *MockNssfApp) SetLogLevel(level string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLogLevel", level)
}

// SetLogLevel indicates an expected call of SetLogLevel.
func (mr *MockNssfAppMockRecorder) SetLogLevel(level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogLevel", reflect.TypeOf((*MockNssfApp)(nil).SetLogLevel), level)
}

// SetReportCaller mocks base method.
func (m *MockNssfApp) SetReportCaller(reportCaller bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetReportCaller", reportCaller)
}

// SetReportCaller indicates an expected call of SetReportCaller.
func (mr *MockNssfAppMockRecorder) SetReportCaller(reportCaller any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReportCaller", reflect.TypeOf((*MockNssfApp)(nil).SetReportCaller), reportCaller)
}

// Start mocks base method.
func (m *MockNssfApp) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockNssfAppMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockNssfApp)(nil).Start))
}

// Terminate mocks base method.
func (m *MockNssfApp) Terminate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Terminate")
}

// Terminate indicates an expected call of Terminate.
func (mr *MockNssfAppMockRecorder) Terminate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockNssfApp)(nil).Terminate))
}
