version: "2"
run:
  concurrency: 4
  go: "1.21"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  sort-order:
    - linter
    - severity
    - file
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - godox
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - predeclared
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -SA1019
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
    depguard:
      rules:
        main:
          list-mode: original
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
    errcheck:
      check-type-assertions: false
      check-blank: true
    goconst:
      min-len: 5
      min-occurrences: 3
      ignore-string-values:
        - get
        - post
        - put
        - delete
        - patch
        - options
        - head
    gocritic:
      disabled-checks:
        - regexpMust
      enabled-tags:
        - diagnostic
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        hugeParam:
          sizeThreshold: 512
        ifElseChain:
          minThreshold: 4
        rangeValCopy:
          sizeThreshold: 512
    godox:
      keywords:
        - FIXME
        - BUG
        - XXX
    govet:
      enable:
        - atomicalign
        - shadow
        - printf
      enable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
        shadow:
          strict: true
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    testpackage:
      skip-regexp: (export|internal)_test\.go
    unused:
      field-writes-are-uses: true
      post-statements-are-reads: true
      exported-fields-are-used: true
      parameters-are-used: true
      local-variables-are-used: true
      generated-is-used: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: ""
  new: false
severity:
  default: error
  rules:
    - linters:
        - mnd
      severity: info
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/free5gc)
      custom-order: true
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
