info:
  version: 1.0.0
  description: BSF initial local configuration

configuration:
  bsfName: BSF # the name of this BSF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.15 # IP used to register to NRF
    bindingIPv4: 127.0.0.15  # IP used to bind the service
    port: 8000 # Port used to bind the service
    tls: # the local path of TLS key
      pem: cert/bsf.pem # BSF TLS Certificate
      key: cert/bsf.key # BSF TLS Private key
  nrfUri: http://127.0.0.10:8000 # a valid URI of NRF
  mongodb:
    name: free5gc                      # name of the mongodb
    url: mongodb://127.0.0.1:27017     # a valid URL of the mongodb
  metrics: # BSF metrics configuration
    enable: true                      # enable/disable metrics server
    scheme: http                       # the protocol for metrics server (http or https)
    bindingIPv4: 0.0.0.0               # IP used to bind the metrics server
    port: 9091                         # Port used to bind the metrics server
    namespace: free5gc                 # metrics namespace
    tls:                               # TLS configuration for metrics server (if https)
      pem: cert/bsf.pem                # BSF TLS Certificate for metrics
      key: cert/bsf.key                # BSF TLS Private key for metrics

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
