/*
 * Namf_MT
 *
 * AMF Mobile Termination Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type EnableUeReachabilityReqData struct {
	Reachability      UeReachability `json:"reachability" bson:"reachability"`
	SupportedFeatures string         `json:"supportedFeatures,omitempty" bson:"supportedFeatures"`
}
