/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RequestPosInfo struct {
	LcsClientType           ExternalClientType `json:"lcsClientType" yaml:"lcsClientType" bson:"lcsClientType"`
	LcsLocation             LocationType       `json:"lcsLocation" yaml:"lcsLocation" bson:"lcsLocation"`
	Supi                    string             `json:"supi,omitempty" yaml:"supi" bson:"supi"`
	Gpsi                    string             `json:"gpsi,omitempty" yaml:"gpsi" bson:"gpsi"`
	Priority                LcsPriority        `json:"priority,omitempty" yaml:"priority" bson:"priority"`
	LcsQoS                  *LocationQoS       `json:"lcsQoS,omitempty" yaml:"lcsQoS" bson:"lcsQoS"`
	VelocityRequested       VelocityRequested  `json:"velocityRequested,omitempty" yaml:"velocityRequested" bson:"velocityRequested"`
	LcsSupportedGADShapes   SupportedGadShapes `json:"lcsSupportedGADShapes,omitempty" yaml:"lcsSupportedGADShapes" bson:"lcsSupportedGADShapes"`
	LocationNotificationUri string             `json:"locationNotificationUri,omitempty" yaml:"locationNotificationUri" bson:"locationNotificationUri"`
	SupportedFeatures       string             `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures"`
}
