/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type MediaComponentResourcesStatus string

// List of MediaComponentResourcesStatus
const (
	MediaComponentResourcesStatus_ACTIVE   MediaComponentResourcesStatus = "ACTIVE"
	MediaComponentResourcesStatus_INACTIVE MediaComponentResourcesStatus = "INACTIVE"
)
