/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CreateUeContextRequest struct {
	JsonData                     *UeContextCreateData `json:"jsonData,omitempty" multipart:"contentType:application/json"`
	BinaryDataN2Information      []byte               `json:"BinaryDataN2Information,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.SourceToTargetData.NgapData.ContentId"`
	BinaryDataN2InformationExt1  []byte               `json:"BinaryDataN2InformationExt1,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.UeRadioCapability.NgapData.ContentId"`
	BinaryDataN2InformationExt2  []byte               `json:"BinaryDataN2InformationExt2,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[0].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt3  []byte               `json:"BinaryDataN2InformationExt3,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[1].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt4  []byte               `json:"BinaryDataN2InformationExt4,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[2].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt5  []byte               `json:"BinaryDataN2InformationExt5,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[3].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt6  []byte               `json:"BinaryDataN2InformationExt6,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[4].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt7  []byte               `json:"BinaryDataN2InformationExt7,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[5].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt8  []byte               `json:"BinaryDataN2InformationExt8,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[6].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt9  []byte               `json:"BinaryDataN2InformationExt9,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[7].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt10 []byte               `json:"BinaryDataN2InformationExt10,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[8].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt11 []byte               `json:"BinaryDataN2InformationExt11,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[9].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt12 []byte               `json:"BinaryDataN2InformationExt12,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[10].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt13 []byte               `json:"BinaryDataN2InformationExt13,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[11].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt14 []byte               `json:"BinaryDataN2InformationExt14,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[12].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt15 []byte               `json:"BinaryDataN2InformationExt15,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[13].N2InfoContent.NgapData.ContentId"`
	BinaryDataN2InformationExt16 []byte               `json:"BinaryDataN2InformationExt16,omitempty" multipart:"contentType:application/vnd.3gpp.ngap,ref:JsonData.PduSessionList[14].N2InfoContent.NgapData.ContentId"`
}
