/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GuamiListCond struct {
	GuamiList []Guami `json:"guamiList" yaml:"guamiList" bson:"guamiList" mapstructure:"GuamiList"`
}
