/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ErrorReport struct {
	Error *ProblemDetails `json:"error,omitempty" yaml:"error" bson:"error" mapstructure:"Error"`
	// Used to report the PCC rule failure.
	RuleReports []RuleReport `json:"ruleReports,omitempty" yaml:"ruleReports" bson:"ruleReports" mapstructure:"RuleReports"`
	// Used to report the session rule failure.
	SessRuleReports []SessionRuleReport `json:"sessRuleReports,omitempty" yaml:"sessRuleReports" bson:"sessRuleReports" mapstructure:"SessRuleReports"`
}
