/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Describes a transfer policy.
type TransferPolicy struct {
	MaxBitRateDl string `json:"maxBitRateDl,omitempty" bson:"maxBitRateDl"`
	MaxBitRateUl string `json:"maxBitRateUl,omitempty" bson:"maxBitRateUl"`
	// Indicates a rating group for the recommended time window.
	RatingGroup int32       `json:"ratingGroup" bson:"ratingGroup"`
	RecTimeInt  *TimeWindow `json:"recTimeInt" bson:"recTimeInt"`
	// Contains an identity of a transfer policy.
	TransPolicyId int32 `json:"transPolicyId" bson:"transPolicyId"`
}
