/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UsageThresholdRm struct {
	// Unsigned integer identifying a period of time in units of seconds with \"nullable=true\" property.
	Duration int32 `json:"duration,omitempty" bson:"duration"`
	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	TotalVolume int64 `json:"totalVolume,omitempty" bson:"totalVolume"`
	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	DownlinkVolume int64 `json:"downlinkVolume,omitempty" bson:"downlinkVolume"`
	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	UplinkVolume int64 `json:"uplinkVolume,omitempty" bson:"uplinkVolume"`
}
