/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type ConditionData struct {

	// Uniquely identifies the condition data within a PDU session.
	CondId string `json:"condId" bson:"condId"`

	ActivationTime *time.Time `json:"activationTime,omitempty" bson:"activationTime"`

	DeactivationTime *time.Time `json:"deactivationTime,omitempty" bson:"deactivationTime"`
}
