/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NfTypeCond struct {
	NfType NfType `json:"nfType" yaml:"nfType" bson:"nfType" mapstructure:"NfType"`
}
