/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UpConfidentiality string

// List of UpConfidentiality
const (
	UpConfidentiality_REQUIRED   UpConfidentiality = "REQUIRED"
	UpConfidentiality_PREFERRED  UpConfidentiality = "PREFERRED"
	UpConfidentiality_NOT_NEEDED UpConfidentiality = "NOT_NEEDED"
)
