/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// describes the event information delivered in the subscription
type AfRoutingRequirement struct {
	AppReloc     bool               `json:"appReloc,omitempty" bson:"appReloc"`
	RouteToLocs  []RouteToLocation  `json:"routeToLocs,omitempty" bson:"routeToLocs"`
	SpVal        *SpatialValidity   `json:"spVal,omitempty" bson:"spVal"`
	TempVals     []TemporalValidity `json:"tempVals,omitempty" bson:"tempVals"`
	UpPathChgSub *UpPathChgEvent    `json:"upPathChgSub,omitempty" bson:"upPathChgSub"`
}
