/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ReportingLevel string

// List of ReportingLevel
const (
	SER_ID_LEVELReportingLevel   ReportingLevel = "SER_ID_LEVEL"
	RAT_GR_LEVELReportingLevel   ReportingLevel = "RAT_GR_LEVEL"
	SPON_CON_LEVELReportingLevel ReportingLevel = "SPON_CON_LEVEL"
)
