/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the UE policy section.
type UePolicySection struct {
	UePolicySectionInfo string `json:"uePolicySectionInfo" bson:"uePolicySectionInfo"`
	Upsi                string `json:"upsi" bson:"upsi"`
}
