/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type UsageMonitoringData struct {

	// Univocally identifies the usage monitoring policy data within a PDU session.
	UmId string `json:"umId" bson:"umId"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThreshold int64 `json:"volumeThreshold,omitempty" bson:"volumeThreshold"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThresholdUplink int64 `json:"volumeThresholdUplink,omitempty" bson:"volumeThresholdUplink"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	VolumeThresholdDownlink int64 `json:"volumeThresholdDownlink,omitempty" bson:"volumeThresholdDownlink"`

	TimeThreshold int32 `json:"timeThreshold,omitempty" bson:"timeThreshold"`

	MonitoringTime *time.Time `json:"monitoringTime,omitempty" bson:"monitoringTime"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThreshold int64 `json:"nextVolThreshold,omitempty" bson:"nextVolThreshold"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThresholdUplink int64 `json:"nextVolThresholdUplink,omitempty" bson:"nextVolThresholdUplink"`

	// Unsigned integer identifying a volume in units of bytes with \"nullable=true\" property.
	NextVolThresholdDownlink int64 `json:"nextVolThresholdDownlink,omitempty" bson:"nextVolThresholdDownlink"`

	NextTimeThreshold int32 `json:"nextTimeThreshold,omitempty" bson:"nextTimeThreshold"`

	InactivityTime int32 `json:"inactivityTime,omitempty" bson:"inactivityTime"`

	// Contains the PCC rule identifier(s) which corresponding service data flow(s) shall be excluded from PDU Session usage monitoring. It is only included in the UsageMonitoringData instance for session level usage monitoring.
	ExUsagePccRuleIds []string `json:"exUsagePccRuleIds,omitempty" bson:"exUsagePccRuleIds"`
}
