/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type N1MessageClass string

// List of N1MessageClass
const (
	N1MessageClass__5_GMM N1MessageClass = "5GMM"
	N1MessageClass_SM N1MessageClass = "SM"
	N1MessageClass_LPP N1MessageClass = "LPP"
	N1MessageClass_SMS N1MessageClass = "SMS"
	N1MessageClass_UPDP N1MessageClass = "UPDP"
)