/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PcscfRestorationNotification struct {
	Supi string `json:"supi" yaml:"supi" bson:"supi" mapstructure:"Supi"`
}
