/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type QosData struct {

	// Univocally identifies the QoS control policy data within a PDU session.
	QosId string `json:"qosId" bson:"qosId"`

	Var5qi int32 `json:"5qi,omitempty" bson:"5qi"`

	MaxbrUl string `json:"maxbrUl,omitempty" bson:"maxbrUl"`

	MaxbrDl string `json:"maxbrDl,omitempty" bson:"maxbrDl"`

	GbrUl string `json:"gbrUl,omitempty" bson:"gbrUl"`

	GbrDl string `json:"gbrDl,omitempty" bson:"gbrDl"`

	Arp *Arp `json:"arp,omitempty" bson:"arp"`

	// Indicates whether notifications are requested from 3GPP NG-RAN when the GFBR can no longer (or again) be guaranteed for a QoS Flow during the lifetime of the QoS Flow.
	Qnc bool `json:"qnc,omitempty" bson:"qnc"`

	PriorityLevel int32 `json:"priorityLevel,omitempty" bson:"priorityLevel"`

	AverWindow int32 `json:"averWindow,omitempty" bson:"averWindow"`

	MaxDataBurstVol int32 `json:"maxDataBurstVol,omitempty" bson:"maxDataBurstVol"`

	// Indicates whether the QoS information is reflective for the corresponding service data flow.
	ReflectiveQos bool `json:"reflectiveQos,omitempty" bson:"reflectiveQos"`

	// Indicates, by containing the same value, what PCC rules may share resource in downlink direction.
	SharingKeyDl string `json:"sharingKeyDl,omitempty" bson:"sharingKeyDl"`

	// Indicates, by containing the same value, what PCC rules may share resource in uplink direction.
	SharingKeyUl string `json:"sharingKeyUl,omitempty" bson:"sharingKeyUl"`

	MaxPacketLossRateDl int32 `json:"maxPacketLossRateDl,omitempty" bson:"maxPacketLossRateDl"`

	MaxPacketLossRateUl int32 `json:"maxPacketLossRateUl,omitempty" bson:"maxPacketLossRateUl"`

	// Indicates that the dynamic PCC rule shall always have its binding with the QoS Flow associated with the default QoS rule
	DefQosFlowIndication bool `json:"defQosFlowIndication,omitempty" bson:"defQosFlowIndication"`
}
