/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ResponseTime string

// List of ResponseTime
const (
	ResponseTime_LOW_DELAY      ResponseTime = "LOW_DELAY"
	ResponseTime_DELAY_TOLERANT ResponseTime = "DELAY_TOLERANT"
)
