/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NasSecurityMode struct {
	IntegrityAlgorithm IntegrityAlgorithm `json:"integrityAlgorithm"`
	CipheringAlgorithm CipheringAlgorithm `json:"cipheringAlgorithm"`
}
