/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// AccNetChargingAddress - Describes the network entity within the access network performing charging
type AccNetChargingAddress struct {
	AnChargIpv4Addr string `json:"anChargIpv4Addr,omitempty" bson:"anChargIpv4Addr"`

	AnChargIpv6Addr string `json:"anChargIpv6Addr,omitempty" bson:"anChargIpv6Addr"`
}
