/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type TerminationCause string

// List of TerminationCause
const (
	TerminationCause_ALL_SDF_DEACTIVATION    TerminationCause = "ALL_SDF_DEACTIVATION"
	TerminationCause_PDU_SESSION_TERMINATION TerminationCause = "PDU_SESSION_TERMINATION"
)
