/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Usage string

// List of Usage
const (
	Usage_UNSUCCESS                                 Usage = "UNSUCCESS"
	Usage_SUCCESS_RESULTS_NOT_USED                  Usage = "SUCCESS_RESULTS_NOT_USED"
	Usage_SUCCESS_RESULTS_USED_TO_VERIFY_LOCATION   Usage = "SUCCESS_RESULTS_USED_TO_VERIFY_LOCATION"
	Usage_SUCCESS_RESULTS_USED_TO_GENERATE_LOCATION Usage = "SUCCESS_RESULTS_USED_TO_GENERATE_LOCATION"
	Usage_SUCCESS_METHOD_NOT_DETERMINED             Usage = "SUCCESS_METHOD_NOT_DETERMINED"
)
