/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// describes the event information delivered in the subscription
type AfEventSubscription struct {
	Event       AfEvent       `json:"event" bson:"event"`
	NotifMethod AfNotifMethod `json:"notifMethod,omitempty" bson:"notifMethod"`
}
