/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NetworkNodeDiameterAddress struct {
	Name  string `json:"name" yaml:"name" bson:"name" mapstructure:"Name"`
	Realm string `json:"realm" yaml:"realm" bson:"realm" mapstructure:"Realm"`
}
