/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AfSigProtocol string

// List of AfSigProtocol
const (
	NO_INFORMATIONAfSigProtocol AfSigProtocol = "NO_INFORMATION"
	SIPAfSigProtocol            AfSigProtocol = "SIP"
)
