/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Rotations struct {
	R1 string `json:"r1" bson:"r1"`
	R2 string `json:"r2" bson:"r2"`
	R3 string `json:"r3" bson:"r3"`
	R4 string `json:"r4" bson:"r4"`
	R5 string `json:"r5" bson:"r5"`
}
