/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type HsmfUpdateError struct {
	Error        *ProblemDetails  `json:"error"`
	Pti          int32            `json:"pti,omitempty"`
	N1smCause    string           `json:"n1smCause,omitempty"`
	N1SmInfoToUe *RefToBinaryData `json:"n1SmInfoToUe,omitempty"`
	BackOffTimer int32            `json:"backOffTimer,omitempty"`
	RecoveryTime *time.Time       `json:"recoveryTime,omitempty"`
}
