/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type ChangeType string

// List of ChangeType
const (
	ChangeType_ADD ChangeType = "ADD"
	ChangeType_MOVE ChangeType = "MOVE"
	ChangeType_REMOVE ChangeType = "REMOVE"
	ChangeType_REPLACE ChangeType = "REPLACE"
)