/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AccuracyFulfilmentIndicator string

// List of AccuracyFulfilmentIndicator
const (
	AccuracyFulfilmentIndicator_FULFILLED     AccuracyFulfilmentIndicator = "REQUESTED_ACCURACY_FULFILLED"
	AccuracyFulfilmentIndicator_NOT_FULFILLED AccuracyFulfilmentIndicator = "REQUESTED_ACCURACY_NOT_FULFILLED"
)
