/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type FlowDirectionRm string

// List of FlowDirectionRm
const (
	FlowDirectionRm_DOWNLINK      FlowDirectionRm = "DOWNLINK"
	FlowDirectionRm_UPLINK        FlowDirectionRm = "UPLINK"
	FlowDirectionRm_BIDIRECTIONAL FlowDirectionRm = "BIDIRECTIONAL"
	FlowDirectionRm_UNSPECIFIED   FlowDirectionRm = "UNSPECIFIED"
)
