/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UpfInfo struct {
	SNssaiUpfInfoList []SnssaiUpfInfoItem `json:"sNssaiUpfInfoList" yaml:"sNssaiUpfInfoList" bson:"sNssaiUpfInfoList" mapstructure:"SNssaiUpfInfoList"`
	SmfServingArea []string `json:"smfServingArea,omitempty" yaml:"smfServingArea" bson:"smfServingArea" mapstructure:"SmfServingArea"`
	InterfaceUpfInfoList []InterfaceUpfInfoItem `json:"interfaceUpfInfoList,omitempty" yaml:"interfaceUpfInfoList" bson:"interfaceUpfInfoList" mapstructure:"InterfaceUpfInfoList"`
	IwkEpsInd bool `json:"iwkEpsInd,omitempty" yaml:"iwkEpsInd" bson:"iwkEpsInd" mapstructure:"IwkEpsInd"`
	PduSessionTypes []PduSessionType `json:"pduSessionTypes,omitempty" yaml:"pduSessionTypes" bson:"pduSessionTypes" mapstructure:"PduSessionTypes"`
}
