/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type FlowInformation struct {

	// Defines a packet filter for an IP flow.Refer to subclause 5.4.2 of 3GPP TS 29.212 [23] for encoding.
	FlowDescription string `json:"flowDescription,omitempty" bson:"flowDescription"`

	EthFlowDescription *EthFlowDescription `json:"ethFlowDescription,omitempty" bson:"ethFlowDescription"`

	// An identifier of packet filter.
	PackFiltId string `json:"packFiltId,omitempty" bson:"packFiltId"`

	// The packet shall be sent to the UE.
	PacketFilterUsage bool `json:"packetFilterUsage,omitempty" bson:"packetFilterUsage"`

	// Contains the Ipv4 Type-of-Service and mask field or the Ipv6 Traffic-Class field and mask field.
	TosTrafficClass string `json:"tosTrafficClass,omitempty" bson:"tosTrafficClass"`

	// the security parameter index of the IPSec packet.
	Spi string `json:"spi,omitempty" bson:"spi"`

	// the Ipv6 flow label header field.
	FlowLabel string `json:"flowLabel,omitempty" bson:"flowLabel"`

	FlowDirection FlowDirectionRm `json:"flowDirection,omitempty" bson:"flowDirection"`
}
