/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UeCampingRep struct {
	AccessType AccessType `json:"accessType,omitempty" bson:"accessType"`

	RatType RatType `json:"ratType,omitempty" bson:"ratType"`

	ServingNetwork *NetworkId `json:"servingNetwork,omitempty" bson:"servingNetwork"`

	UserLocationInfo *UserLocation `json:"userLocationInfo,omitempty" bson:"userLocationInfo"`

	UeTimeZone string `json:"ueTimeZone,omitempty" bson:"ueTimeZone"`
}
