/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NotifCondition struct {
	MonitoredAttributes []string `json:"monitoredAttributes,omitempty" bson:"monitoredAttributes"`

	UnmonitoredAttributes []string `json:"unmonitoredAttributes,omitempty" bson:"unmonitoredAttributes"`
}
