/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type GuamiListCond struct {
	GuamiList *[]Guami `json:"guamiList" bson:"guamiList"`
}
