/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AmfEventNotification struct {
	NotifyCorrelationId           string           `json:"notifyCorrelationId,omitempty" bson:"notifyCorrelationId" `
	SubsChangeNotifyCorrelationId string           `json:"subsChangeNotifyCorrelationId,omitempty" bson:"subsChangeNotifyCorrelationId" `
	ReportList                    []AmfEventReport `json:"reportList,omitempty" bson:"reportList" `
}
