/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UeContextTransferStatus string

// List of UeContextTransferStatus
const (
	UeContextTransferStatus_TRANSFERRED     UeContextTransferStatus = "TRANSFERRED"
	UeContextTransferStatus_NOT_TRANSFERRED UeContextTransferStatus = "NOT_TRANSFERRED"
)
