/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Milenage struct {
	Op        *Op        `json:"op,omitempty" bson:"op"`
	Rotations *Rotations `json:"rotations,omitempty" bson:"rotations"`
	Constants *Constants `json:"constants,omitempty" bson:"constants"`
}
