/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type BsfInfo struct {
	DnnList []string `json:"dnnList,omitempty" bson:"dnnList"`

	IpDomainList []string `json:"ipDomainList,omitempty" bson:"ipDomainList"`

	Ipv4AddressRanges *[]Ipv4AddressRange `json:"ipv4AddressRanges,omitempty" bson:"ipv4AddressRanges"`

	Ipv6PrefixRanges *[]Ipv6PrefixRange `json:"ipv6PrefixRanges,omitempty" bson:"ipv6PrefixRanges"`
}
