/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type TransportProtocol string

// List of TransportProtocol
const (
	TransportProtocol_TCP TransportProtocol = "TCP"
)