/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PolicyAssociationReleaseCause string

// List of PolicyAssociationReleaseCause
const (
	PolicyAssociationReleaseCause_UNSPECIFIED      PolicyAssociationReleaseCause = "UNSPECIFIED"
	PolicyAssociationReleaseCause_UE_SUBSCRIPTION  PolicyAssociationReleaseCause = "UE_SUBSCRIPTION"
	PolicyAssociationReleaseCause_INSUFFICIENT_RES PolicyAssociationReleaseCause = "INSUFFICIENT_RES"
)
