/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ResourceStatus string

// List of ResourceStatus
const (
	ResourceStatus_RELEASED ResourceStatus = "RELEASED"
)
