/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SponsoringStatus string

// List of SponsoringStatus
const (
	SponsoringStatus_DISABLED SponsoringStatus = "SPONSOR_DISABLED"
	SponsoringStatus_ENABLED  SponsoringStatus = "SPONSOR_ENABLED"
)
