/*
 * Npcf_SMPolicyControl
 *
 * Session Management Policy Control Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SessionRuleReport struct {
	// Contains the identifier of the affected session rule(s).
	RuleIds             []string               `json:"ruleIds" yaml:"ruleIds" bson:"ruleIds" mapstructure:"RuleIds"`
	RuleStatus          RuleStatus             `json:"ruleStatus" yaml:"ruleStatus" bson:"ruleStatus" mapstructure:"RuleStatus"`
	SessRuleFailureCode SessionRuleFailureCode `json:"sessRuleFailureCode,omitempty" yaml:"sessRuleFailureCode" bson:"sessRuleFailureCode" mapstructure:"SessRuleFailureCode"`
}
