/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Identifies the service requirements of an Individual Application Session Context.
type AppSessionContextReqData struct {
	// Contains an AF application identifier.
	AfAppId   string                `json:"afAppId,omitempty" bson:"afAppId"`
	AfRoutReq *AfRoutingRequirement `json:"afRoutReq,omitempty" bson:"afRoutReq"`
	// Contains an identity of an application service provider.
	AspId string `json:"aspId,omitempty" bson:"aspId"`
	// string identifying a BDT Reference ID as defined in subclause 5.3.3 of 3GPP TS 29.154.
	BdtRefId      string                    `json:"bdtRefId,omitempty" bson:"bdtRefId"`
	Dnn           string                    `json:"dnn,omitempty" bson:"dnn"`
	EvSubsc       *EventsSubscReqData       `json:"evSubsc,omitempty" bson:"evSubsc"`
	MedComponents map[string]MediaComponent `json:"medComponents,omitempty" bson:"medComponents"`
	IpDomain      string                    `json:"ipDomain,omitempty" bson:"ipDomain"`
	// indication of MPS service request
	MpsId     string  `json:"mpsId,omitempty" bson:"mpsId"`
	NotifUri  string  `json:"notifUri" bson:"notifUri"`
	SliceInfo *Snssai `json:"sliceInfo,omitempty" bson:"sliceInfo"`
	// Contains an identity of a sponsor.
	SponId     string           `json:"sponId,omitempty" bson:"sponId"`
	SponStatus SponsoringStatus `json:"sponStatus,omitempty" bson:"sponStatus"`
	Supi       string           `json:"supi,omitempty" bson:"supi"`
	SuppFeat   string           `json:"suppFeat" bson:"suppFeat"`
	UeIpv4     string           `json:"ueIpv4,omitempty" bson:"ueIpv4"`
	UeIpv6     string           `json:"ueIpv6,omitempty" bson:"ueIpv6"`
	UeMac      string           `json:"ueMac,omitempty" bson:"ueMac"`
}
