/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type NotifiedPosInfo struct {
	LocationEvent           LocationEvent                   `json:"locationEvent" yaml:"locationEvent" bson:"locationEvent"`
	Supi                    string                          `json:"supi,omitempty" yaml:"supi" bson:"supi"`
	Gpsi                    string                          `json:"gpsi,omitempty" yaml:"gpsi" bson:"gpsi"`
	Pei                     string                          `json:"pei,omitempty" yaml:"pei" bson:"pei"`
	LocationEstimate        *GeographicArea                 `json:"locationEstimate,omitempty" yaml:"locationEstimate" bson:"locationEstimate"`
	AgeOfLocationEstimate   int32                           `json:"ageOfLocationEstimate,omitempty" yaml:"ageOfLocationEstimate" bson:"ageOfLocationEstimate"`
	VelocityEstimate        *VelocityEstimate               `json:"velocityEstimate,omitempty" yaml:"velocityEstimate" bson:"velocityEstimate"`
	PositioningDataList     []PositioningMethodAndUsage     `json:"positioningDataList,omitempty" yaml:"positioningDataList" bson:"positioningDataList"`
	GnssPositioningDataList []GnssPositioningMethodAndUsage `json:"gnssPositioningDataList,omitempty" yaml:"gnssPositioningDataList" bson:"gnssPositioningDataList"`
	Ecgi                    *Ecgi                           `json:"ecgi,omitempty" yaml:"ecgi" bson:"ecgi"`
	Ncgi                    *Ncgi                           `json:"ncgi,omitempty" yaml:"ncgi" bson:"ncgi"`
	ServingNode             string                          `json:"servingNode,omitempty" yaml:"servingNode" bson:"servingNode"`
	CivicAddress            *CivicAddress                   `json:"civicAddress,omitempty" yaml:"civicAddress" bson:"civicAddress"`
	BarometricPressure      int32                           `json:"barometricPressure,omitempty" yaml:"barometricPressure" bson:"barometricPressure"`
	Altitude                float32                         `json:"altitude,omitempty" yaml:"altitude" bson:"altitude"`
}
