/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type UeContextCreateData struct {
	UeContext          *UeContext        `json:"ueContext"`
	TargetId           *NgRanTargetId    `json:"targetId"`
	SourceToTargetData *N2InfoContent    `json:"sourceToTargetData"`
	PduSessionList     []N2SmInformation `json:"pduSessionList,omitempty"`
	N2NotifyUri        string            `json:"n2NotifyUri,omitempty"`
	UeRadioCapability  *N2InfoContent    `json:"ueRadioCapability,omitempty"`
	NgapCause          *NgApCause        `json:"ngapCause,omitempty"`
	SupportedFeatures  string            `json:"supportedFeatures,omitempty"`
}
