/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AreaOfValidity struct {
	TaiList []Tai `json:"taiList,omitempty"`
}
