/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SmContextStatusNotification struct {
	StatusInfo *StatusInfo `json:"statusInfo"`
}
