/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type VectorAlgorithm string

// List of VectorAlgorithm
const (
	VectorAlgorithm_MILENAGE VectorAlgorithm = "MILENAGE"
	VectorAlgorithm_TUAK     VectorAlgorithm = "TUAK"
)
