/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type NrfSubscriptionData struct {
	NfStatusNotificationUri string `json:"nfStatusNotificationUri" bson:"nfStatusNotificationUri"`

	SubscrCond *interface{} `json:"subscrCond,omitempty" bson:"subscrCond"`

	SubscriptionId string `json:"subscriptionId" bson:"subscriptionId"`

	ValidityTime *time.Time `json:"validityTime,omitempty" bson:"validityTime"`

	ReqNotifEvents []NotificationEventType `json:"reqNotifEvents,omitempty" bson:"reqNotifEvents"`

	PlmnId *PlmnId `json:"plmnId,omitempty" bson:"plmnId"`

	NotifCondition *NotifCondition `json:"notifCondition,omitempty" bson:"notifCondition"`

	ReqNfType NfType `json:"reqNfType,omitempty" bson:"reqNfType"`

	ReqNfFqdn string `json:"reqNfFqdn,omitempty" bson:"reqNfFqdn"`
}
