/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PositioningMethodAndUsage struct {
	Method PositioningMethod `json:"method" yaml:"method" bson:"method"`
	Mode   PositioningMode   `json:"mode" yaml:"mode" bson:"mode"`
	Usage  Usage             `json:"usage" yaml:"usage" bson:"usage"`
}
