/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CipheringAlgorithm string

// List of CipheringAlgorithm
const (
	CipheringAlgorithm_NEA0 CipheringAlgorithm = "NEA0"
	CipheringAlgorithm_NEA1 CipheringAlgorithm = "NEA1"
	CipheringAlgorithm_NEA2 CipheringAlgorithm = "NEA2"
	CipheringAlgorithm_NEA3 CipheringAlgorithm = "NEA3"
)
