/*
 * Npcf_PolicyAuthorization Service API
 *
 * This is the Policy Authorization Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Indicates whether the QoS targets for a GRB flow are not guaranteed or guaranteed again
type QosNotificationControlInfo struct {

	// An array of PCC rule id references to the PCC rules associated with the QoS notification control info.
	RefPccRuleIds []string `json:"refPccRuleIds" bson:"refPccRuleIds"`

	NotifType QosNotifType `json:"notifType" bson:"notifType"`

	// Represents the content version of some content.
	ContVer int32   `json:"contVer,omitempty" bson:"contVer"`
	Flows   []Flows `json:"flows,omitempty" bson:"flows"`
}
