/*
 * NRF OAuth2
 *
 * NRF OAuth2 Authorization
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AccessTokenErr struct {
	Error string `json:"error" bson:"error"`

	ErrorDescription string `json:"error_description,omitempty" bson:"error_description"`

	ErrorUri string `json:"error_uri,omitempty" bson:"error_uri"`
}
