/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Link struct {
	Href string `json:"href,omitempty" yaml:"href" bson:"href" mapstructure:"Href"`
}
