/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type HoState string

// List of HoState
const (
	HoState_NONE      HoState = "NONE"
	HoState_PREPARING HoState = "PREPARING"
	HoState_PREPARED  HoState = "PREPARED"
	HoState_COMPLETED HoState = "COMPLETED"
	HoState_CANCELLED HoState = "CANCELLED"
)
