/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SmsSupport string

// List of SmsSupport
const (
	SmsSupport__3_GPP    SmsSupport = "3GPP"
	SmsSupport_NON_3_GPP SmsSupport = "NON_3GPP"
	SmsSupport_BOTH      SmsSupport = "BOTH"
	SmsSupport_NONE      SmsSupport = "NONE"
)
