/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type EpsInterworkingIndication string

// List of EpsInterworkingIndication
const (
	EpsInterworkingIndication_NONE        EpsInterworkingIndication = "NONE"
	EpsInterworkingIndication_WITH_N26    EpsInterworkingIndication = "WITH_N26"
	EpsInterworkingIndication_WITHOUT_N26 EpsInterworkingIndication = "WITHOUT_N26"
)
