/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type EmergencyInfo struct {
	PgwFqdn       string     `json:"pgwFqdn,omitempty" yaml:"pgwFqdn" bson:"pgwFqdn" mapstructure:"PgwFqdn"`
	PgwIpAddress  *IpAddress `json:"pgwIpAddress,omitempty" yaml:"pgwIpAddress" bson:"pgwIpAddress" mapstructure:"PgwIpAddress"`
	SmfInstanceId string     `json:"smfInstanceId,omitempty" yaml:"smfInstanceId" bson:"smfInstanceId" mapstructure:"SmfInstanceId"`
}
