/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Ipv6PrefixRange struct {
	Start string `json:"start,omitempty" bson:"start"`

	End string `json:"end,omitempty" bson:"end"`
}
