/*
 * Nudm_UECM
 *
 * Nudm Context Management Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DeregistrationData struct {
	DeregReason DeregistrationReason `json:"deregReason" yaml:"deregReason" bson:"deregReason" mapstructure:"DeregReason"`
	AccessType  AccessType           `json:"accessType" yaml:"accessType" bson:"accessType" mapstructure:"AccessType"`
}
