/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PwsResponseData struct {
	NgapMessageType   int32  `json:"ngapMessageType"`
	SerialNumber      int32  `json:"serialNumber"`
	MessageIdentifier int32  `json:"messageIdentifier"`
	UnknownTaiList    *[]Tai `json:"unknownTaiList,omitempty"`
}
