/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RmState string

// List of RmState
const (
	RmState_REGISTERED   RmState = "REGISTERED"
	RmState_DEREGISTERED RmState = "DEREGISTERED"
)
