/*
 * Namf_Communication
 *
 * AMF Communication Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LocationFilter string

// List of LocationFilter
const (
	LocationFilter_TAI      LocationFilter = "TAI"
	LocationFilter_CELL_ID  LocationFilter = "CELL_ID"
	LocationFilter_N3_IWF   LocationFilter = "N3IWF"
	LocationFilter_UE_IP    LocationFilter = "UE_IP"
	LocationFilter_UDP_PORT LocationFilter = "UDP_PORT"
)
