/*
 * NRF OAuth2
 *
 * NRF OAuth2 Authorization
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AccessTokenRsp struct {

	// JWS Compact Serialized representation of JWS signed JSON object (AccessTokenClaims)
	AccessToken string `json:"access_token" bson:"access_token"`

	TokenType string `json:"token_type" bson:"token_type"`

	ExpiresIn int32 `json:"expires_in,omitempty" bson:"expires_in"`

	Scope string `json:"scope,omitempty" bson:"scope"`
}
