/*
 * Namf_Location
 *
 * AMF Location Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type VelocityRequested string

// List of VelocityRequested
const (
	VelocityRequested_NOT_REQUESTED VelocityRequested = "VELOCITY_IS_NOT_REQUESTED"
	VelocityRequested_REQUESTED     VelocityRequested = "VELOCITY_IS_REQUESTED"
)
