/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type DefaultNotificationSubscription struct {
	NotificationType NotificationType `json:"notificationType" bson:"notificationType"`

	CallbackUri string `json:"callbackUri" bson:"callbackUri"`

	N1MessageClass N1MessageClass `json:"n1MessageClass,omitempty" bson:"n1MessageClass"`

	N2InformationClass N2InformationClass `json:"n2InformationClass,omitempty" bson:"n2InformationClass"`
}
