/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func (s *Server) getEventExposureRoutes() []Route {
	return []Route{
		{
			Name:    "Index",
			Method:  http.MethodGet,
			Pattern: "/",
			APIFunc: func(c *gin.Context) {
				c.JSON(http.StatusOK, gin.H{"status": "Service Available"})
			},
		},
		{
			Name:    "CreateIndividualSubcription",
			Method:  http.MethodPost,
			Pattern: "/subscriptions",
			APIFunc: s.HTTPCreateIndividualSubcription,
		},
		{
			Name:    "DeleteIndividualSubcription",
			Method:  http.MethodDelete,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPDeleteIndividualSubcription,
		},
		{
			Name:    "GetIndividualSubcription",
			Method:  http.MethodGet,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPGetIndividualSubcription,
		},
		{
			Name:    "ReplaceIndividualSubcription",
			Method:  http.MethodPut,
			Pattern: "/subscriptions/:subId",
			APIFunc: s.HTTPReplaceIndividualSubcription,
		},
	}
}

// SubscriptionsPost -
func (s *Server) HTTPCreateIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}

// SubscriptionsSubIdDelete -
func (s *Server) HTTPDeleteIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}

// SubscriptionsSubIdGet -
func (s *Server) HTTPGetIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}

// SubscriptionsSubIdPut -
func (s *Server) HTTPReplaceIndividualSubcription(c *gin.Context) {
	c.JSON(http.StatusNotImplemented, gin.H{})
}
