version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - godox
    - lll
    - misspell
    - nakedret
    - noctx
    - predeclared
    - unconvert
    - whitespace
  settings:
    staticcheck:
      checks:
        - all
        - -QF1008
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
    errcheck:
      check-type-assertions: false
      check-blank: true
    funlen:
      lines: 60
      statements: 40
    gocognit:
      min-complexity: 10
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - regexpMust
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
    gocyclo:
      min-complexity: 10
    godox:
      keywords:
        - FIXME
        - BUG
        - XXX
    govet:
      enable:
        - atomicalign
      disable:
        - shadow
      enable-all: false
      disable-all: false
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 120
      tab-width: 1
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 4
    testpackage:
      skip-regexp: (export|internal)_test\.go
    whitespace:
      multi-if: false
      multi-func: false
    wsl:
      strict-append: true
      allow-assign-and-call: true
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: true
      allow-separated-leading-comment: false
      allow-cuddle-declarations: false
      force-err-cuddling: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: ""
  new: false
severity:
  default: error
  rules:
    - linters:
        - mnd
      severity: ignore
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/free5gc)
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/org/project
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
