name: Cfg-go

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CFG_GENERATOR_DIR: config/cfg-generator

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CFG_GENERATOR_DIR }}
    strategy:
      matrix:
        go: [ '1.26.2' ]

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4
          working-directory: ${{ env.CFG_GENERATOR_DIR }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Make
        run: make
